# Generated by Django 4.2.1 on 2023-05-21 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_customuser_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
